[package]
name = "rusty-book-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"


[dependencies.tokio]
version = "1"
features = [
    "full"
]

[dependencies.axum]
version = "0.7"
features = [
    "macros"
]


[dev-dependencies]
rstest = "0.23"